export const INDIAN_STATES = [
  { name: "Andaman and Nicobar Islands", code: "35" },
  { name: "Andhra Pradesh", code: "37" },
  { name: "Arunachal Pradesh", code: "12" },
  { name: "Assam", code: "18" },
  { name: "Bihar", code: "10" },
  { name: "Chandigarh", code: "04" },
  { name: "Chhattisgarh", code: "22" },
  { name: "Dadra and Nagar Haveli and Daman and Diu", code: "26" },
  { name: "Delhi", code: "07" },
  { name: "Goa", code: "30" },
  { name: "Gujarat", code: "24" },
  { name: "Haryana", code: "06" },
  { name: "Himachal Pradesh", code: "02" },
  { name: "Jammu and Kashmir", code: "01" },
  { name: "Jharkhand", code: "20" },
  { name: "Karnataka", code: "29" },
  { name: "Kerala", code: "32" },
  { name: "Ladakh", code: "38" },
  { name: "Lakshadweep", code: "31" },
  { name: "Madhya Pradesh", code: "23" },
  { name: "Maharashtra", code: "27" },
  { name: "Manipur", code: "14" },
  { name: "Meghalaya", code: "17" },
  { name: "Mizoram", code: "15" },
  { name: "Nagaland", code: "13" },
  { name: "Odisha", code: "21" },
  { name: "Puducherry", code: "34" },
  { name: "Punjab", code: "03" },
  { name: "Rajasthan", code: "08" },
  { name: "Sikkim", code: "11" },
  { name: "Tamil Nadu", code: "33" },
  { name: "Telangana", code: "36" },
  { name: "Tripura", code: "16" },
  { name: "Uttar Pradesh", code: "09" },
  { name: "Uttarakhand", code: "05" },
  { name: "West Bengal", code: "19" }
].sort((a, b) => a.name.localeCompare(b.name));

export const STATE_NAMES = INDIAN_STATES.map(s => s.name);

export const COMMON_HSN_CODES = [
  { code: "9983", label: "Graphic Design / IT Services" },
  { code: "9987", label: "Maintenance & Repair Services" },
  { code: "9984", label: "Software Publishing / Licenses" },
  { code: "9973", label: "Leasing or Rental Services" },
  { code: "9982", label: "Legal & Accounting Services" },
  { code: "9985", label: "Support / Recruitment Services" },
  { code: "9981", label: "R&D Services" },
  { code: "4901", label: "Printed Books / Brochures" },
  { code: "4911", label: "Other Printed Matter (Cards/Posters)" },
  { code: "8471", label: "Computers / Peripherals" },
  { code: "8517", label: "Telephones / Mobile Devices" },
  { code: "8523", label: "Software on Media (CD/DVD)" },
  { code: "9988", label: "Manufacturing / Job Work" },
  { code: "9989", label: "Printing & Publishing Services" },
].sort((a, b) => a.label.localeCompare(b.label));
